### ISSUE TITLE
Join Wahoo?

### ISSUE THREAD

**Issue by ghost** [dorentus/.fish#1]
We are still relatively new in town, and just getting started, but we are more stable than the other options, namely OMF. I think some of these functions could be turned into a handful of Wahoo plugins or maybe some could be even make it to core. We are always accepting feature request and feedback. I would love if you could give [Wahoo](https://github.com/fish-shell/wahoo/blob/master/FAQ.md) a look.

Regards :smile:

**Comment by dorentus** [comment]
Thanks for reaching me :smile:

I tried Wahoo for several minutes and it looks promising. I'll take a deeper look at it and try converting some functions here into Wahoo plugins.

**Comment by dorentus** [comment]
@bucaran I've made a theme here: https://github.com/dorentus/theme-clownfish

Is there any chance it goes in to the wahoo theme gallery?

**Comment by ghost** [comment]
@dorentus Hi. It's been a while and a lot of things happened. Wahoo is still lurking around, but I am working now on a new system [Fisherman](http://fisherman.sh), please check it out.

I'll fork your theme and send you a PR so you know how to make it work in Fisherman.
